#!/bin/bash
# Setting environment variables
# Following variables must be set:
# HOST, USER, SSH_KEY, BINDIR, BASEDIR, CODEDIR
. yarrow_config


if [[ -z $1 ]]; then
  echo "Getting aggregated log from a finished yarrow session. Log files will be extracted from logs of instances and merged into one file log.txt"
  echo "Usage: $0 <session_name> <destination_path>"
  exit 1
fi


if [[ -z $2 ]]; then
  TARGET=./$1.txt
else
  TARGET=$2
fi

# Specifying option "StrictHostKeyChecking accept-new" to avoid questions about host's key

echo "Aggregating logs from runners into one file"
ssh -o "StrictHostKeyChecking accept-new" -i "$SSH_KEY" "$USER"@"$HOST" "cd $BASEDIR/$1; $BINDIR/../client/yarrow_agglog >log.txt"
#exec yarrow_agglog >log.txt
scp -i "$SSH_KEY" scp://"$USER"@"$HOST"/$BASEDIR/$1/log.txt $TARGET

