#!/bin/bash
# Setting environment variables
# Following variables must be set:
# HOST, USER, SSH_KEY, BINDIR, BASEDIR, CODEDIR
. yarrow_config


if [[ -z $1 ]]; then
  echo "Specify name of the testing script and its parameters if required."
  echo "Usage: $0 test_script.js param1=value1 param2=value2 ..."
  exit 1
fi

SCRIPT_FILE=`basename $1`
if [[ ! $SCRIPT_FILE =~ .*\.js ]]; then
  echo "First parameter must be JavaScript file to run: $SCRIPT_FILE"
  exit 1
fi

# Calling 'create_session' script; specifying option "StrictHostKeyChecking accept-new" to avoid questions about host's key
SESSION_NAME=`ssh -o "StrictHostKeyChecking accept-new" -i "$SSH_KEY" "$USER"@"$HOST" "$BINDIR"/create_session`
echo "Created test session: $SESSION_NAME"

echo "Copying code files to the session code storage"
params=""
for a in $@; do
  if [[ -f "$a" ]]; then
    scp -i "$SSH_KEY" $a scp://"$USER"@"$HOST"/$BASEDIR/$SESSION_NAME/$CODEDIR/`basename $a`
  else
    params="$params $a"
  fi
done

echo "Sending parameters: "$params

# Running the script with all the params that were passed and additional two params: 'session' and 'script'
ssh -i "$SSH_KEY" "$USER"@"$HOST" "$BINDIR"/run_test session=$SESSION_NAME script=$SCRIPT_FILE $params
