#!/bin/bash
# Extracting logs from all tgz files of runners and aggregating it into one log for the session
ls *.tgz | awk '{print substr($0,1,index($0,".tgz")-1)}' | while read -r file; do
    tar -O -xzf "$file".tgz "$file"/log.txt
done

