#!/bin/sh
# Following environment variables have to be set:
# Y_HOST - IP address or name of the "Controller" machine
# Y_SESSION - name of the session (session folder on the "Controller" machine)
# Y_SCRIPT - name of the Node.JS script to run
RUNDIR=`uname -n | cut -d'.' -f1`-`date +"%y%m%d-%H%M"`
VMID=`uname -n | cut -d'.' -f1 | sed 's/[^1-9]*//'`
USER=yarrow
SSH_KEY="/home/yarrow/.ssh/yarrow-runner-ssh-key"
BASEDIR=/var/yarrow/session
CODEDIR=code
LOCALDIR=/var/yarrow/tests
scp -o "StrictHostKeyChecking accept-new" -i "$SSH_KEY" scp://"$USER"@"$Y_HOST"/$BASEDIR/$Y_SESSION/$CODEDIR/* $LOCALDIR
Xvfb :0 -screen 0 1920x1080x24 2>x_err &
DISPLAY=:0; export DISPLAY
cd $LOCALDIR
mkdir $RUNDIR
cd $RUNDIR
node ../$Y_SCRIPT $@ vmid=$VMID >log.txt 2>&1
cd ..
tar -czf $RUNDIR.tgz $RUNDIR
scp -i "$SSH_KEY" $LOCALDIR/$RUNDIR.tgz scp://"$USER"@"$Y_HOST"/$BASEDIR/$Y_SESSION/
