#!/bin/bash
BINDIR=/opt/yarrow/controller
VARDIR=/var/yarrow
LOGDIR=$VARDIR/log
SESSIONDIR=$VARDIR/session

# creating a directory for logs
if [ ! -d $LOGDIR ]; then
  mkdir $LOGDIR
  chmod 777 $LOGDIR
fi

# creating a directory for sessions
if [ ! -d /var/yarrow/session ]; then
  mkdir /var/yarrow/session
  chmod 777 /var/yarrow/session
fi

# creating the session and echoing session name back to the calling script
SESSION_NAME=`whoami`-`date +"%y%m%d-%H%M%S"`
mkdir $SESSIONDIR/$SESSION_NAME
mkdir $SESSIONDIR/$SESSION_NAME/code
chmod 777 $SESSIONDIR/$SESSION_NAME
echo $SESSION_NAME
