#!/bin/bash
BINDIR=/opt/yarrow/controller
VARDIR=/var/yarrow
LOGDIR=$VARDIR/log

# starting services to be used by running tests
cd $BINDIR
bash -c "./start_services >>$LOGDIR/services.log"

# run the test
echo "Params: "$@
#node run_tests_stub.js host=`hostname -I` $@
node run_tests.js host=`hostname -I` $@
