#!/bin/bash
# starting services to be used by running tests
cd $BINDIR
bash -c "./start_services >>$LOGDIR/services.log"

# run the test
cd /opt/yarrow/controller
echo "Params: "$@
#node run_tests_stub.js host=`hostname -I` $@
node run_tests.js host=`hostname -I` $@
