#!/bin/bash
#
# Start index service
LOGDIR=/var/yarrow/log/
YI_PORT=8400
SRVNAME=`curl -s http://localhost:$YI_PORT/`
if [ "$SRVNAME" != "yarrow-index" ]; then
  echo "Starting index service - " `date`
  node ../lib/index.js >>$LOGDIR/service-index.log &
fi
